export const DUMMY_BOARDS = [
  {
    id: "dummy-1",
    name: "boilerplate",
    shortLink: "roadmap",
    workspaceName: "boilerplate",
    starred: true,
    closed: false,
    workspaceId: "ws-demo",
  },
  {
    id: "dummy-2",
    name: "Sprint board",
    shortLink: "sprint",
    workspaceName: "Engineering",
    closed: false,
    workspaceId: "ws-demo",
  },
  {
    id: "dummy-3",
    name: "Design backlog",
    shortLink: "design",
    workspaceName: "Design",
    closed: false,
    workspaceId: "ws-demo",
  },
  {
    id: "dummy-4",
    name: "Marketing ideas",
    shortLink: "marketing",
    workspaceName: "Growth",
    closed: false,
    workspaceId: "ws-demo",
  },
  {
    id: "dummy-5",
    name: "Engineering tasks",
    shortLink: "eng",
    workspaceName: "Engineering",
    starred: true,
    closed: false,
    workspaceId: "ws-demo",
  },
  {
    id: "dummy-6",
    name: "Team retrospective",
    shortLink: "retro",
    workspaceName: "People",
    closed: false,
    workspaceId: "ws-demo",
  },
  {
    id: "dummy-7",
    name: "Personal todos",
    shortLink: "todos",
    workspaceName: "Personal",
    closed: false,
    workspaceId: "ws-demo",
  },
] as const;
